wandb:
    project: pico-llm-sweeps
    name: null

system:
    device_id: cuda:0
    to_compile: True

data:
    input_files: [] # list of files
    tinystories_weight: 0.5
    train_subset_size: 20000
    test_split: 0.2 # 20% split? may need some change
    batch_size: 16
    block_size: 1024

model:
    type: transformer
    block_size: 1024
    n_layer: 4
    n_embd: 1024
    n_head: 2


algorithm:
    lr: 3e-4
    log_steps: 100
    sample_interval: 30
    max_steps_per_epoch: null
    epochs: 3
